### PR TITLE
Documented OSIC blog process

### PR DESCRIPTION
**Pull request by RobinJoe**
Adapting Process Work Stream content on blog writing for the
/osic-docs repository.

Updating the README file in the /osic-docs repository to describe
blog writing and white paper writing resources.

Closes issue https://github.com/rackerlabs/docs-workstream/issues/224

### CODE REVIEW

**Comment by RobinJoe** [comment]
Closes - https://github.com/rackerlabs/docs-workstream/issues/224

**Review by asettle — APPROVED** [review]
Thanks Joe!

**Comment by asettle** [comment]
@mrhillsman - starting here, working on templates, thoughts? :)

**Comment by asettle** [comment]
Hey Joe - I updated the README and didn't realise it would conflict, sorry! Fixed the conflict now, should be fine!

**Pull request merged**
